/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanage;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author motev
 */
public class AdminHandle extends javax.swing.JFrame {

    /**
     * Creates new form AdminHandle
     */
    public AdminHandle() {
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tableNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("ENTER THE TABLE NAME THAT YOU WANT TO DELETE :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("ENTER THE TABLE NAME :");

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("DELETE ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("jLabel6");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "adminmain", "user_signup", "doctor_record", "patient_record", "appointment1_module", "checkup_module" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "adminmain", "user_signup", "doctor_record", "patient_record", "appointment1_module", "checkup_module" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("SELECT TABLE THAT YOU WANT TO PERFORM OPERTION ON IT :");

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("DELETE");

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CREATE ");

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 599));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("ADMIN HANDLE ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("FOR CREATING ALL THE TABLES FROM HOSPITAL DATABASE CLICK ON BELOW BUTTON :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 620, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CREATE ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 110, 40));

        jButton6.setBackground(new java.awt.Color(255, 102, 102));
        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, 90, 30));

        jButton7.setBackground(new java.awt.Color(51, 102, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 80, 30));

        jButton8.setBackground(new java.awt.Color(0, 255, 102));
        jButton8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton8.setText("CREATE HOPITAL DATEBASE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 230, 40));

        jButton9.setBackground(new java.awt.Color(255, 102, 102));
        jButton9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton9.setText("DELETE HOSPITAL DATABASE");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 240, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanage/adminhandle.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try {
            // Replace placeholders with your actual database credentials
            String url = "jdbc:mysql://localhost:3306/hospital";
            String user = "root";
            String password = "";

             // Establish connection
             Connection connection = DriverManager.getConnection(url, user, password);
            
            String tableName = tableNameField.getText().trim(); // Get table name from the text field
            if (!tableName.isEmpty()) {
                // Create SQL statement to delete the entire table
                String sql = "DROP TABLE " + tableName;

                // Create statement
                Statement statement = connection.createStatement();

                // Execute the statement
                statement.executeUpdate(sql);

                // Show success message
                JOptionPane.showMessageDialog(this, "Table deleted successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a table name.");
            }
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error deleting table: " + e.getMessage());
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
     try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
    Statement st = conn.createStatement();
    String sql = "DROP DATABASE hi"; // Corrected SQL statement
    PreparedStatement ptst = conn.prepareStatement(sql);
    
    // Execute the prepared statement
    ptst.executeUpdate();
    
    // Optionally, you can close the resources
    ptst.close();
    conn.close();
    
    JOptionPane.showMessageDialog(null, "Database deleted successfully");
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
    Statement st = conn.createStatement();
    String sql = "CREATE DATABASE hi"; // Corrected SQL statement
    PreparedStatement ptst = conn.prepareStatement(sql);
    
    // Execute the prepared statement
    ptst.executeUpdate();
    
    // Optionally, you can close the resources
    ptst.close();
    conn.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
    Statement st = conn.createStatement();
    
    // Table for the adminmain
    String createTableSql = "CREATE TABLE IF NOT EXISTS adminmain (ID INT PRIMARY KEY, NAME VARCHAR(255) NOT NULL, PASSWORD VARCHAR(255) NOT NULL)";
    st.executeUpdate(createTableSql);
    // Values for the adminmain
    String insertDataSql = "INSERT INTO adminmain(ID, NAME, PASSWORD) VALUES (1, 'Admin18', 'Admin18')";
    st.executeUpdate(insertDataSql);
    
    
    
    // Table for the user_signup
    String createTableSql1 = "CREATE TABLE IF NOT EXISTS user_signup(ID INT PRIMARY KEY, NAME VARCHAR(255) NOT NULL , EMAIL VARCHAR(255) NOT NULL ,PASSWORD VARCHAR(255) NOT NULL)";
    st.executeUpdate(createTableSql1);
    
    
    
    // Table for the doctor record
    String createTableSql2 = "CREATE TABLE IF NOT EXISTS doctor_record(ID INT PRIMARY KEY, NAME VARCHAR(255) NOT NULL ,GENDER VARCHAR(255) NOT NULL , SPECIALIZATION VARCHAR(255) NOT NULL ,MOBILENO VARCHAR(255) NOT NULL , CITY VARCHAR(255) NOT NULL)";
    st.executeUpdate(createTableSql2);
    
    
    
    
     // Table for the PATIENT RECORD 
    String createTableSql3 = "CREATE TABLE IF NOT EXISTS patient_record(ID INT PRIMARY KEY, NAME VARCHAR(255) NOT NULL  ,MOBILENO VARCHAR(255) NOT NULL ,AGE VARCHAR(255) NOT NULL ,GENDER VARCHAR(255) NOT NULL ,ILLNESS VARCHAR(255) NOT NULL , ADMITDATE VARCHAR(255) NOT NULL , ADMITTIME VARCHAR(255) NOT NULL)";
    st.executeUpdate(createTableSql3);
    
    
    
     // Table for the appointment module
    String createTableSql4 = "CREATE TABLE IF NOT EXISTS appointment1_module(ID INT PRIMARY KEY, NAME VARCHAR(255) NOT NULL  ,MOBILENO VARCHAR(255) NOT NULL ,AGE VARCHAR(255) NOT NULL , ADDRESS VARCHAR(255) NOT NULL  , GENDER VARCHAR(255) NOT NULL ,ILLNESS VARCHAR(255) NOT NULL , DATE VARCHAR(255) NOT NULL ,DAY VARCHAR(255) NOT NULL , TIME VARCHAR(255) NOT NULL)";
    st.executeUpdate(createTableSql4);
    
    
    
     
    // Table for the checkup_module
    String createTableSql5 = "CREATE TABLE IF NOT EXISTS checkup_module(ID INT PRIMARY KEY, MEDICINE VARCHAR(255) NOT NULL , RECOMMANDATION VARCHAR(255) NOT NULL ,FEE VARCHAR(255) NOT NULL)";
    st.executeUpdate(createTableSql5);
    
    
    JOptionPane.showMessageDialog(null, "Data added successfully");
    
    conn.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        AdminHandleMain obj = new AdminHandleMain();
        obj.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        loginpage obj = new loginpage();
        obj.setVisible(true);
        dispose();
        
                
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHandle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHandle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHandle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHandle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHandle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tableNameField;
    // End of variables declaration//GEN-END:variables

 private void setIconImage() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("hmsmainlogo.png")));
    }
}
