/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanage;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author motev
 */
public class EditPatient extends javax.swing.JFrame {

    /**
     * Creates new form EditPatient
     */
    public EditPatient() {
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pi1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pm = new javax.swing.JTextField();
        pa = new javax.swing.JLabel();
        pa1 = new javax.swing.JTextField();
        pg1 = new javax.swing.JTextField();
        pg = new javax.swing.JLabel();
        pi = new javax.swing.JLabel();
        pi2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        dat = new javax.swing.JTextField();
        pa2 = new javax.swing.JLabel();
        tim = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(860, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("EDIT PATIENT DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 396, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("ENTER PATIENT ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 103, 181, 35));
        getContentPane().add(pi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 186, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 204));
        jLabel3.setText("PATIENT NAME :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 153, 35));
        getContentPane().add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 186, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("MOBILE NO :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 153, 35));
        getContentPane().add(pm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 186, 35));

        pa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pa.setForeground(new java.awt.Color(204, 0, 204));
        pa.setText("AGE :");
        getContentPane().add(pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 108, 35));

        pa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pa1ActionPerformed(evt);
            }
        });
        getContentPane().add(pa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 186, 35));

        pg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pg1ActionPerformed(evt);
            }
        });
        getContentPane().add(pg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 186, 35));

        pg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pg.setForeground(new java.awt.Color(204, 0, 204));
        pg.setText("GENDER :");
        getContentPane().add(pg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 90, 38));

        pi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pi.setForeground(new java.awt.Color(204, 0, 204));
        pi.setText("ILLNESS :");
        getContentPane().add(pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 100, 35));
        getContentPane().add(pi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 260, 186, 35));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 95, 37));

        jButton2.setBackground(new java.awt.Color(0, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 103, 43));

        jButton3.setBackground(new java.awt.Color(255, 51, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("LOGOUT");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, -1, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("CURRENT DATE :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 153, 35));
        getContentPane().add(dat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 186, 35));

        pa2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pa2.setForeground(new java.awt.Color(204, 0, 204));
        pa2.setText("CURRENT TIME :");
        getContentPane().add(pa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 35));

        tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timActionPerformed(evt);
            }
        });
        getContentPane().add(tim, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 186, 35));

        jButton4.setBackground(new java.awt.Color(51, 255, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 87, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanage/Edit p&d.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Patients obj = new Patients();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String pid = pi1.getText();
        String pname = pn.getText();
        String pgender = pg1.getText();
        String pillness = pi2.getText();
        String page= pa1.getText();
        String pdate= dat.getText();
        String ptime= tim.getText();

        
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
            String sql = "UPDATE patient_record SET NAME='" + pname + "', GENDER='" + pgender + "',ILLNESS='" + pillness + "', AGE='" + page + "',ADMITDATE='" + pdate + "' ,ADMITTIME='" + ptime + "'WHERE id='" + pid + "'";

            PreparedStatement ptst =conn.prepareStatement(sql);
            ptst.execute();

            JOptionPane.showMessageDialog(null,"Data Upddated Successfully");

           pi1.setText("");pn.setText("");pg1.setText("");
            pi2.setText("");pa1.setText("");dat.setText("");tim.setText("");
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            
            
                        JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void pa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pa1ActionPerformed

    private void timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
         
        String ID = pi1.getText();
        
         try{
             
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital","root","");
            Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("select * from patient_record WHERE id='"+ID+"'");
           

             if(rs.next()){
                 pn.setText(rs.getString(2));
                 pm.setText(rs.getString(3));
                 pa1.setText(rs.getString(4));
                 pg1.setText(rs.getString(5));
                 pi2.setText(rs.getString(6));
                 dat.setText(rs.getString(7));
                 tim.setText(rs.getString(8 ));

             }
             
             else{
            JOptionPane.showMessageDialog(null, "Patient ID does not exist"); 
             }
         }catch(Exception e){
             
         }
        
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void pg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pg1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel pa;
    private javax.swing.JTextField pa1;
    private javax.swing.JLabel pa2;
    private javax.swing.JLabel pg;
    private javax.swing.JTextField pg1;
    private javax.swing.JLabel pi;
    private javax.swing.JTextField pi1;
    private javax.swing.JTextField pi2;
    private javax.swing.JTextField pm;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField tim;
    // End of variables declaration//GEN-END:variables

 private void setIconImage() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("hmsmainlogo.png")));
    }
}
